'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ManagementService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ManagementService.IManagementService", SessionMode:=System.ServiceModel.SessionMode.NotAllowed)>  _
    Public Interface IManagementService
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IManagementService/StartFullset")>  _
        Sub StartFullset(ByVal comment As String)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IManagementService/StartFullset")>  _
        Function StartFullsetAsync(ByVal comment As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IManagementService/StopFullsetAsync")>  _
        Sub StopFullsetAsync()
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IManagementService/StopFullsetAsync")>  _
        Function StopFullsetAsyncAsync() As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IManagementServiceChannel
        Inherits ManagementService.IManagementService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ManagementServiceClient
        Inherits System.ServiceModel.ClientBase(Of ManagementService.IManagementService)
        Implements ManagementService.IManagementService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub StartFullset(ByVal comment As String) Implements ManagementService.IManagementService.StartFullset
            MyBase.Channel.StartFullset(comment)
        End Sub
        
        Public Function StartFullsetAsync(ByVal comment As String) As System.Threading.Tasks.Task Implements ManagementService.IManagementService.StartFullsetAsync
            Return MyBase.Channel.StartFullsetAsync(comment)
        End Function
        
        Public Sub StopFullsetAsync() Implements ManagementService.IManagementService.StopFullsetAsync
            MyBase.Channel.StopFullsetAsync
        End Sub
        
        Public Function StopFullsetAsyncAsync() As System.Threading.Tasks.Task Implements ManagementService.IManagementService.StopFullsetAsyncAsync
            Return MyBase.Channel.StopFullsetAsyncAsync
        End Function
    End Class
End Namespace
