'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace AlarmService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AlarmService.IAlarmService", SessionMode:=System.ServiceModel.SessionMode.NotAllowed)>  _
    Public Interface IAlarmService
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IAlarmService/Acknowledge")>  _
        Sub Acknowledge(ByVal parameterName As String)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IAlarmService/Acknowledge")>  _
        Function AcknowledgeAsync(ByVal parameterName As String) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAlarmServiceChannel
        Inherits AlarmService.IAlarmService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AlarmServiceClient
        Inherits System.ServiceModel.ClientBase(Of AlarmService.IAlarmService)
        Implements AlarmService.IAlarmService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub Acknowledge(ByVal parameterName As String) Implements AlarmService.IAlarmService.Acknowledge
            MyBase.Channel.Acknowledge(parameterName)
        End Sub
        
        Public Function AcknowledgeAsync(ByVal parameterName As String) As System.Threading.Tasks.Task Implements AlarmService.IAlarmService.AcknowledgeAsync
            Return MyBase.Channel.AcknowledgeAsync(parameterName)
        End Function
    End Class
End Namespace
