'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ControlService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ControlService.IControlService")>  _
    Public Interface IControlService
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IControlService/Reset")>  _
        Sub Reset()
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, AsyncPattern:=true, Action:="http://tempuri.org/IControlService/Reset")>  _
        Function BeginReset(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndReset(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IControlService/Shutdown")>  _
        Sub Shutdown()
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, AsyncPattern:=true, Action:="http://tempuri.org/IControlService/Shutdown")>  _
        Function BeginShutdown(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndShutdown(ByVal result As System.IAsyncResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IControlServiceChannel
        Inherits ControlService.IControlService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ControlServiceClient
        Inherits System.ServiceModel.ClientBase(Of ControlService.IControlService)
        Implements ControlService.IControlService
        
        Private onBeginResetDelegate As BeginOperationDelegate
        
        Private onEndResetDelegate As EndOperationDelegate
        
        Private onResetCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginShutdownDelegate As BeginOperationDelegate
        
        Private onEndShutdownDelegate As EndOperationDelegate
        
        Private onShutdownCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event ResetCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event ShutdownCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Sub Reset() Implements ControlService.IControlService.Reset
            MyBase.Channel.Reset
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginReset(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ControlService.IControlService.BeginReset
            Return MyBase.Channel.BeginReset(callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndReset(ByVal result As System.IAsyncResult) Implements ControlService.IControlService.EndReset
            MyBase.Channel.EndReset(result)
        End Sub
        
        Private Function OnBeginReset(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginReset(callback, asyncState)
        End Function
        
        Private Function OnEndReset(ByVal result As System.IAsyncResult) As Object()
            Me.EndReset(result)
            Return Nothing
        End Function
        
        Private Sub OnResetCompleted(ByVal state As Object)
            If (Not (Me.ResetCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ResetCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ResetAsync()
            Me.ResetAsync(Nothing)
        End Sub
        
        Public Overloads Sub ResetAsync(ByVal userState As Object)
            If (Me.onBeginResetDelegate Is Nothing) Then
                Me.onBeginResetDelegate = AddressOf Me.OnBeginReset
            End If
            If (Me.onEndResetDelegate Is Nothing) Then
                Me.onEndResetDelegate = AddressOf Me.OnEndReset
            End If
            If (Me.onResetCompletedDelegate Is Nothing) Then
                Me.onResetCompletedDelegate = AddressOf Me.OnResetCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginResetDelegate, Nothing, Me.onEndResetDelegate, Me.onResetCompletedDelegate, userState)
        End Sub
        
        Public Sub Shutdown() Implements ControlService.IControlService.Shutdown
            MyBase.Channel.Shutdown
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginShutdown(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ControlService.IControlService.BeginShutdown
            Return MyBase.Channel.BeginShutdown(callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndShutdown(ByVal result As System.IAsyncResult) Implements ControlService.IControlService.EndShutdown
            MyBase.Channel.EndShutdown(result)
        End Sub
        
        Private Function OnBeginShutdown(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginShutdown(callback, asyncState)
        End Function
        
        Private Function OnEndShutdown(ByVal result As System.IAsyncResult) As Object()
            Me.EndShutdown(result)
            Return Nothing
        End Function
        
        Private Sub OnShutdownCompleted(ByVal state As Object)
            If (Not (Me.ShutdownCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ShutdownCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ShutdownAsync()
            Me.ShutdownAsync(Nothing)
        End Sub
        
        Public Overloads Sub ShutdownAsync(ByVal userState As Object)
            If (Me.onBeginShutdownDelegate Is Nothing) Then
                Me.onBeginShutdownDelegate = AddressOf Me.OnBeginShutdown
            End If
            If (Me.onEndShutdownDelegate Is Nothing) Then
                Me.onEndShutdownDelegate = AddressOf Me.OnEndShutdown
            End If
            If (Me.onShutdownCompletedDelegate Is Nothing) Then
                Me.onShutdownCompletedDelegate = AddressOf Me.OnShutdownCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginShutdownDelegate, Nothing, Me.onEndShutdownDelegate, Me.onShutdownCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
